{-# LANGUAGE TupleSections #-}
module Fragem.Syntax.FromMidiSpec (spec) where

import Control.DeepSeq
import Data.Maybe

import Fragem.Syntax.FromMidi

import Test.Hspec
import Test.QuickCheck
import Test.QuickCheck.Monadic

parse1 :: FilePath -> PropertyM IO Bool
parse1 file = do
  res <- run (fromMidi file)
  case res `deepseq` res of
    Left err -> run (putStrLn (file ++ "; " ++ err))
             >> return False
    Right _  -> return True

spec :: Spec
spec = do
  describe "fromMidi" $ do
    it "parses the dataset with no errors" $ once $ monadicIO $
      do res <- flip mapM dataset parse1
         return (and res)

datasetWithErrors :: [String]
datasetWithErrors =
 [ "dataset/jsbach/suites/airgstr4.mid"
 , "dataset/jsbach/wtcbki/fugue19.mid"
 , "dataset/jsbach/wtcbki/fugue15.mid"
 , "dataset/jsbach/wtcbki/fugue13.mid"
 , "dataset/jsbach/wtcbki/prelude2.mid"
 , "dataset/jsbach/wtcbki/fugue11.mid"
 ]

-- TODO: Automate this with the directory library.
--       Currently I generate this with the following shell command:
--
-- > find dataset -name "*.mid" | sed 's/^/ , "/' | sed 's/$/"/' | xclip -sel clip
dataset :: [String]
dataset = 
 [ "dataset/jsbach/organ/prefug8.mid"
 , "dataset/jsbach/organ/prefug5.mid"
 , "dataset/jsbach/organ/orgel19.mid"
 , "dataset/jsbach/organ/prefug4.mid"
 , "dataset/jsbach/organ/prefug7.mid"
 , "dataset/jsbach/organ/catech4.mid"
 , "dataset/jsbach/organ/catech9.mid"
 , "dataset/jsbach/organ/catech6.mid"
 , "dataset/jsbach/organ/trio3c.mid"
 , "dataset/jsbach/organ/prefug1.mid"
 , "dataset/jsbach/organ/trio3a.mid"
 , "dataset/jsbach/organ/toccata1.mid"
 , "dataset/jsbach/organ/catech8.mid"
 , "dataset/jsbach/organ/catech10.mid"
 , "dataset/jsbach/organ/trio3b.mid"
 , "dataset/jsbach/organ/prefug2.mid"
 , "dataset/jsbach/organ/passac.mid"
 , "dataset/jsbach/organ/catech7.mid"
 , "dataset/jsbach/organ/catechor.mid"
 , "dataset/jsbach/organ/toccata2.mid"
 , "dataset/jsbach/organ/schub6.mid"
 , "dataset/jsbach/organ/catech1.mid"
 , "dataset/jsbach/organ/catech2.mid"
 , "dataset/jsbach/organ/prefug3.mid"
 , "dataset/jsbach/organ/catech11.mid"
 , "dataset/jsbach/organ/schub5.mid"
 , "dataset/jsbach/organ/catech3.mid"
 , "dataset/jsbach/organ/catech5.mid"
 , "dataset/jsbach/organ/prefug6.mid"
 , "dataset/jsbach/partitas/cou1.mid"
 , "dataset/jsbach/partitas/men1.mid"
 , "dataset/jsbach/partitas/ron2.mid"
 , "dataset/jsbach/partitas/sin2.mid"
 , "dataset/jsbach/partitas/gig1.mid"
 , "dataset/jsbach/partitas/sar2.mid"
 , "dataset/jsbach/partitas/cap2.mid"
 , "dataset/jsbach/partitas/sar1.mid"
 , "dataset/jsbach/partitas/all1.mid"
 , "dataset/jsbach/partitas/pre1.mid"
 , "dataset/jsbach/partitas/cou2.mid"
 , "dataset/jsbach/partitas/all2.mid"
 , "dataset/jsbach/cantatas/jesu1.mid"
 , "dataset/jsbach/cantatas/jesu2.mid"
 , "dataset/jsbach/cellosui/04prelud.mid"
 , "dataset/jsbach/cellosui/01gigue.mid"
 , "dataset/jsbach/cellosui/01prelud.mid"
 , "dataset/jsbach/cellosui/04bourre.mid"
 , "dataset/jsbach/cellosui/04saraba.mid"
 , "dataset/jsbach/cellosui/01minuet.mid"
 , "dataset/jsbach/cellosui/01allema.mid"
 , "dataset/jsbach/cellosui/01couran.mid"
 , "dataset/jsbach/cellosui/01saraba.mid"
 , "dataset/jsbach/cellosui/04allema.mid"
 , "dataset/jsbach/cellosui/04couran.mid"
 , "dataset/jsbach/cellosui/04gigue.mid"
 , "dataset/jsbach/invent/invent8.mid"
 , "dataset/jsbach/invent/invent13.mid"
 , "dataset/jsbach/invent/invent7.mid"
 , "dataset/jsbach/invent/invent11.mid"
 , "dataset/jsbach/invent/invent9.mid"
 , "dataset/jsbach/invent/invent6.mid"
 , "dataset/jsbach/invent/invent12.mid"
 , "dataset/jsbach/invent/invent4.mid"
 , "dataset/jsbach/invent/invent3.mid"
 , "dataset/jsbach/invent/invent2.mid"
 , "dataset/jsbach/invent/invent1.mid"
 , "dataset/jsbach/invent/invent5.mid"
 , "dataset/jsbach/invent/invent14.mid"
 , "dataset/jsbach/invent/invent15.mid"
 , "dataset/jsbach/invent/invent10.mid"
 , "dataset/jsbach/gold/var25.mid"
 , "dataset/jsbach/gold/var21c7.mid"
 , "dataset/jsbach/gold/var24c8.mid"
 , "dataset/jsbach/gold/var10.mid"
 , "dataset/jsbach/gold/var12c4.mid"
 , "dataset/jsbach/gold/var8.mid"
 , "dataset/jsbach/gold/var3c1.mid"
 , "dataset/jsbach/gold/aria.mid"
 , "dataset/jsbach/gold/var16.mid"
 , "dataset/jsbach/gold/var4.mid"
 , "dataset/jsbach/gold/var5.mid"
 , "dataset/jsbach/gold/var7.mid"
 , "dataset/jsbach/gold/var2.mid"
 , "dataset/jsbach/gold/var28.mid"
 , "dataset/jsbach/gold/goldberg.mid"
 , "dataset/jsbach/gold/var27c9.mid"
 , "dataset/jsbach/gold/var9c3.mid"
 , "dataset/jsbach/gold/var20.mid"
 , "dataset/jsbach/gold/var17.mid"
 , "dataset/jsbach/gold/var23.mid"
 , "dataset/jsbach/gold/var22.mid"
 , "dataset/jsbach/gold/var19.mid"
 , "dataset/jsbach/gold/var1.mid"
 , "dataset/jsbach/gold/var18c6.mid"
 , "dataset/jsbach/gold/var30.mid"
 , "dataset/jsbach/gold/var14.mid"
 , "dataset/jsbach/gold/var11.mid"
 , "dataset/jsbach/gold/var13.mid"
 , "dataset/jsbach/gold/var15c5.mid"
 , "dataset/jsbach/gold/var6c2.mid"
 , "dataset/jsbach/gold/var29.mid"
 , "dataset/jsbach/gold/var26.mid"
 , "dataset/jsbach/fugues/fuguecm.mid"
 , "dataset/jsbach/fugues/fuguegm.mid"
 , "dataset/jsbach/aof/can3.mid"
 , "dataset/jsbach/aof/inver2.mid"
 , "dataset/jsbach/aof/unfin.mid"
 , "dataset/jsbach/aof/tri1.mid"
 , "dataset/jsbach/aof/dou1.mid"
 , "dataset/jsbach/aof/cnt2.mid"
 , "dataset/jsbach/aof/reg1.mid"
 , "dataset/jsbach/aof/reg2.mid"
 , "dataset/jsbach/aof/can2.mid"
 , "dataset/jsbach/aof/tri2.mid"
 , "dataset/jsbach/aof/cnt3.mid"
 , "dataset/jsbach/aof/can1.mid"
 , "dataset/jsbach/aof/mir1.mid"
 , "dataset/jsbach/aof/inver1.mid"
 , "dataset/jsbach/aof/mir2.mid"
 , "dataset/jsbach/aof/dou2.mid"
 , "dataset/jsbach/aof/can4.mid"
 , "dataset/jsbach/aof/cnt1.mid"
 , "dataset/jsbach/brandenb/brand43.mid"
 , "dataset/jsbach/brandenb/brand53.mid"
 , "dataset/jsbach/brandenb/brand51.mid"
 , "dataset/jsbach/brandenb/brand52.mid"
 , "dataset/jsbach/brandenb/brand42.mid"
 , "dataset/jsbach/brandenb/brand2.mid"
 , "dataset/jsbach/brandenb/brand1.mid"
 , "dataset/jsbach/brandenb/brand41.mid"
 , "dataset/jsbach/brandenb/brand3.mid"
 , "dataset/jsbach/sinfon/sinfon11.mid"
 , "dataset/jsbach/sinfon/sinfon6.mid"
 , "dataset/jsbach/sinfon/sinfon9.mid"
 , "dataset/jsbach/sinfon/sinfon13.mid"
 , "dataset/jsbach/sinfon/sinfon7.mid"
 , "dataset/jsbach/sinfon/sinfon2.mid"
 , "dataset/jsbach/sinfon/sinfon4.mid"
 , "dataset/jsbach/sinfon/sinfon1.mid"
 , "dataset/jsbach/sinfon/sinfon3.mid"
 , "dataset/jsbach/sinfon/sinfon10.mid"
 , "dataset/jsbach/sinfon/sinfon15.mid"
 , "dataset/jsbach/sinfon/sinfon5.mid"
 , "dataset/jsbach/sinfon/sinfon14.mid"
 , "dataset/jsbach/sinfon/sinfon8.mid"
 , "dataset/jsbach/sinfon/sinfon12.mid"
 , "dataset/jsbach/wtcbki/fugue4.mid"
 , "dataset/jsbach/wtcbki/fugue7.mid"
 , "dataset/jsbach/wtcbki/prelude3.mid"
 , "dataset/jsbach/wtcbki/prelude7.mid"
 , "dataset/jsbach/wtcbki/fugue1.mid"
 , "dataset/jsbach/wtcbki/prelude8.mid"
 , "dataset/jsbach/wtcbki/prelude5.mid"
 , "dataset/jsbach/wtcbki/fugue2.mid"
 , "dataset/jsbach/wtcbki/fugue17.mid"
 , "dataset/jsbach/wtcbki/fugue20.mid"
 , "dataset/jsbach/wtcbki/prelude1.mid"
 , "dataset/jsbach/wtcbki/fugue9.mid"
 , "dataset/jsbach/wtcbki/fugue24.mid"
 , "dataset/jsbach/wtcbki/fugue21.mid"
 , "dataset/jsbach/wtcbki/fugue6.mid"
 , "dataset/jsbach/wtcbki/fugue10.mid"
 , "dataset/jsbach/wtcbki/fugue16.mid"
 , "dataset/jsbach/wtcbki/fugue3.mid"
 , "dataset/jsbach/wtcbki/prelude4.mid"
 , "dataset/jsbach/wtcbki/fugue8.mid"
 , "dataset/jsbach/wtcbki/fugue5.mid"
 , "dataset/jsbach/wtcbki/fugue12.mid"
 , "dataset/jsbach/wtcbki/fugue18.mid"
 , "dataset/jsbach/wtcbki/prelude9.mid"
 , "dataset/jsbach/wtcbki/fugue22.mid"
 , "dataset/jsbach/wtcbki/fugue14.mid"
 , "dataset/jsbach/wtcbki/fugue23.mid"
 , "dataset/jsbach/wtcbki/prelude6.mid"
 , "dataset/jsbach/wtcbkii/fugue4.mid"
 , "dataset/jsbach/wtcbkii/fugue7.mid"
 , "dataset/jsbach/wtcbkii/prelude3.mid"
 , "dataset/jsbach/wtcbkii/prelude7.mid"
 , "dataset/jsbach/wtcbkii/fugue1.mid"
 , "dataset/jsbach/wtcbkii/prelude8.mid"
 , "dataset/jsbach/wtcbkii/prelude5.mid"
 , "dataset/jsbach/wtcbkii/fugue2.mid"
 , "dataset/jsbach/wtcbkii/prelude1.mid"
 , "dataset/jsbach/wtcbkii/fugue9.mid"
 , "dataset/jsbach/wtcbkii/fugue6.mid"
 , "dataset/jsbach/wtcbkii/fugue10.mid"
 , "dataset/jsbach/wtcbkii/fugue3.mid"
 , "dataset/jsbach/wtcbkii/prelude4.mid"
 , "dataset/jsbach/wtcbkii/fugue8.mid"
 , "dataset/jsbach/wtcbkii/prelude2.mid"
 , "dataset/jsbach/wtcbkii/fugue5.mid"
 , "dataset/jsbach/wtcbkii/fugue12.mid"
 , "dataset/jsbach/wtcbkii/prelude9.mid"
 , "dataset/jsbach/wtcbkii/fugue11.mid"
 , "dataset/jsbach/wtcbkii/prelude6.mid"
 , "dataset/jsbach/organcho/bsgjg_a.mid"
 , "dataset/jsbach/organcho/bsgjg_j.mid"
 , "dataset/jsbach/organcho/bsgjg_l.mid"
 , "dataset/jsbach/organcho/bsgjg_c.mid"
 , "dataset/jsbach/organcho/bsgjg_f.mid"
 , "dataset/jsbach/organcho/bsgjg_k.mid"
 , "dataset/jsbach/organcho/bsgjg_i.mid"
 , "dataset/jsbach/organcho/bsgjg_e.mid"
 , "dataset/jsbach/organcho/bsgjg_g.mid"
 , "dataset/jsbach/organcho/bsgjg_d.mid"
 , "dataset/jsbach/organcho/bsgjg_b.mid"
 , "dataset/jsbach/organcho/bsgjg_h.mid"
 , "dataset/jsbach/chorales/09ermunt.mid"
 , "dataset/jsbach/chorales/08freuet.mid"
 , "dataset/jsbach/chorales/03achgot.mid"
 , "dataset/jsbach/chorales/11jesu.mid"
 , "dataset/jsbach/chorales/05anwass.mid"
 , "dataset/jsbach/chorales/10austie.mid"
 , "dataset/jsbach/chorales/13allein.mid"
 , "dataset/jsbach/chorales/01ausmei.mid"
 , "dataset/jsbach/chorales/02ichdan.mid"
 , "dataset/jsbach/chorales/14oherre.mid"
 , "dataset/jsbach/chorales/07nunlob.mid"
 , "dataset/jsbach/chorales/12puerna.mid"
 , "dataset/jsbach/chorales/04esistd.mid"
 , "dataset/jsbach/chorales/06christ.mid"
 , "dataset/jsbach/chorales/15christ.mid"
 , "dataset/czerny/36-96.Czerny 40.mid"
 , "dataset/czerny/36-96.Czerny 45.mid"
 , "dataset/czerny/36-96.Czerny 14.mid"
 , "dataset/czerny/36-96.Czerny 12.mid"
 , "dataset/czerny/36-96.Czerny 77.mid"
 , "dataset/czerny/36-96.Czerny 81.mid"
 , "dataset/czerny/36-96.Czerny 56.mid"
 , "dataset/czerny/36-96.Czerny 58.mid"
 , "dataset/czerny/36-96.Czerny 51.mid"
 , "dataset/czerny/36-96.Czerny 33.mid"
 , "dataset/czerny/36-96.Czerny 68.mid"
 , "dataset/czerny/36-96.Czerny 15.mid"
 , "dataset/czerny/36-96.Czerny 66.mid"
 , "dataset/czerny/36-96.Czerny 55.mid"
 , "dataset/czerny/36-96.Czerny 16.mid"
 , "dataset/czerny/36-96.Czerny 27.mid"
 , "dataset/czerny/36-96.Czerny 70.mid"
 , "dataset/czerny/36-96.Czerny 21.mid"
 , "dataset/czerny/36-96.Czerny 08.mid"
 , "dataset/czerny/36-96.Czerny 28.mid"
 , "dataset/czerny/36-96.Czerny 32.mid"
 , "dataset/czerny/36-96.Czerny 30.mid"
 , "dataset/czerny/36-96.Czerny 74.mid"
 , "dataset/czerny/36-96.Czerny 69.mid"
 , "dataset/czerny/36-96.Czerny 86.mid"
 , "dataset/czerny/36-96.Czerny 35.mid"
 , "dataset/czerny/36-96.Czerny 80.mid"
 , "dataset/czerny/36-96.Czerny 52.mid"
 , "dataset/czerny/36-96.Czerny 41.mid"
 , "dataset/czerny/36-96.Czerny 63.mid"
 , "dataset/czerny/36-96.Czerny 61.mid"
 , "dataset/czerny/36-96.Czerny 42.mid"
 , "dataset/czerny/36-96.Czerny 72.mid"
 , "dataset/czerny/36-96.Czerny 82.mid"
 , "dataset/czerny/36-96.Czerny 03.mid"
 , "dataset/czerny/36-96.Czerny 71.mid"
 , "dataset/czerny/36-96.Czerny 09.mid"
 , "dataset/czerny/36-96.Czerny 17.mid"
 , "dataset/czerny/36-96.Czerny 04.mid"
 , "dataset/czerny/36-96.Czerny 84.mid"
 , "dataset/czerny/36-96.Czerny 29.mid"
 , "dataset/czerny/36-96.Czerny 10.mid"
 , "dataset/czerny/36-96.Czerny 73.mid"
 , "dataset/czerny/36-96.Czerny 98.mid"
 , "dataset/czerny/36-96.Czerny 100.mid"
 , "dataset/czerny/36-96.Czerny 92.mid"
 , "dataset/czerny/36-96.Czerny 22.mid"
 , "dataset/czerny/36-96.Czerny 62.mid"
 , "dataset/czerny/36-96.Czerny 20.mid"
 , "dataset/czerny/36-96.Czerny 46.mid"
 , "dataset/czerny/36-96.Czerny 25.mid"
 , "dataset/czerny/36-96.Czerny 01.mid"
 , "dataset/czerny/36-96.Czerny 89.mid"
 , "dataset/czerny/36-96.Czerny 34.mid"
 , "dataset/czerny/36-96.Czerny 02.mid"
 , "dataset/czerny/36-96.Czerny 96.mid"
 , "dataset/czerny/36-96.Czerny 99.mid"
 , "dataset/czerny/36-96.Czerny 76.mid"
 , "dataset/czerny/36-96.Czerny 79.mid"
 , "dataset/czerny/36-96.Czerny 19.mid"
 , "dataset/czerny/36-96.Czerny 47.mid"
 , "dataset/czerny/36-96.Czerny 83.mid"
 , "dataset/czerny/36-96.Czerny 91.mid"
 , "dataset/czerny/36-96.Czerny 43.mid"
 , "dataset/czerny/36-96.Czerny 18.mid"
 , "dataset/czerny/36-96.Czerny 64.mid"
 , "dataset/czerny/36-96.Czerny 60.mid"
 , "dataset/czerny/36-96.Czerny 07.mid"
 , "dataset/czerny/36-96.Czerny 37.mid"
 , "dataset/czerny/36-96.Czerny 06.mid"
 , "dataset/czerny/36-96.Czerny 24.mid"
 , "dataset/czerny/36-96.Czerny 44.mid"
 , "dataset/czerny/36-96.Czerny 49.mid"
 , "dataset/czerny/36-96.Czerny 48.mid"
 , "dataset/czerny/36-96.Czerny 50.mid"
 , "dataset/czerny/36-96.Czerny 87.mid"
 , "dataset/czerny/36-96.Czerny 59.mid"
 , "dataset/czerny/36-96.Czerny 54.mid"
 , "dataset/czerny/36-96.Czerny 75.mid"
 , "dataset/czerny/36-96.Czerny 94.mid"
 , "dataset/czerny/36-96.Czerny 05.mid"
 , "dataset/czerny/36-96.Czerny 26.mid"
 , "dataset/czerny/36-96.Czerny 67.mid"
 , "dataset/czerny/36-96.Czerny 53.mid"
 , "dataset/czerny/36-96.Czerny 90.mid"
 , "dataset/czerny/36-96.Czerny 78.mid"
 , "dataset/czerny/36-96.Czerny 36.mid"
 , "dataset/czerny/36-96.Czerny 95.mid"
 , "dataset/czerny/36-96.Czerny 57.mid"
 , "dataset/czerny/36-96.Czerny 88.mid"
 , "dataset/czerny/36-96.Czerny 85.mid"
 , "dataset/czerny/36-96.Czerny 31.mid"
 , "dataset/czerny/36-96.Czerny 97.mid"
 , "dataset/czerny/36-96.Czerny 65.mid"
 , "dataset/czerny/36-96.Czerny 39.mid"
 , "dataset/czerny/36-96.Czerny 93.mid"
 , "dataset/czerny/36-96.Czerny 38.mid"
 , "dataset/czerny/36-96.Czerny 11.mid"
 , "dataset/czerny/36-96.Czerny 23.mid"
 , "dataset/czerny/36-96.Czerny 13.mid"
 , "dataset/sample/sample2.mid"
 , "dataset/sample/sample3.mid"
 , "dataset/sample/sample1.mid"
 , "dataset/hanon/Hanon 10.mid"
 , "dataset/hanon/Hanon 16.mid"
 , "dataset/hanon/Hanon 9.mid"
 , "dataset/hanon/Hanon 22.mid"
 , "dataset/hanon/Hanon 19.mid"
 , "dataset/hanon/Hanon 20.mid"
 , "dataset/hanon/Hanon 1.mid"
 , "dataset/hanon/Hanon 7.mid"
 , "dataset/hanon/Hanon 8.mid"
 , "dataset/hanon/Hanon 5.mid"
 , "dataset/hanon/Hanon 21.mid"
 , "dataset/hanon/Hanon 15.mid"
 , "dataset/hanon/Hanon 13.mid"
 , "dataset/hanon/Hanon 14.mid"
 , "dataset/hanon/Hanon 18.mid"
 , "dataset/hanon/Hanon 6.mid"
 , "dataset/hanon/Hanon 3.mid"
 , "dataset/hanon/Hanon 17.mid"
 , "dataset/hanon/Hanon 2.mid"
 , "dataset/hanon/Hanon 11.mid"
 , "dataset/hanon/Hanon 4.mid"
 ]
